allowed:
  origins: https://jahanzaib.org, https://www.jahanzaib.org

resilience4j.ratelimiter:
  instances:
    steamApiLimiter:
      limit-for-period: 5
      limit-refresh-period: 1m
      timeout-duration: 0
    prayerTimesApiLimiter:
      limit-for-period: 50
      limit-refresh-period: 1m
      timeout-duration: 0

steam:
  api-key: <API_KEY>
  user-id: <USER_ID>

spring:
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect